apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
  namespace: default
data:
  # Key-value pairs of your configuration data
  DATABASE_URL: "mysql://localhost:3306/mydatabase"
  API_URL: "http://api.example.com"
  TIMEOUT: "30s"
